// Generated by firmware/tools/make_sounds.py - lengths (ms) of the one-shot main tracks.
// Replace with your own font's values if you swap the sound files.
#pragma once
#define SND_IGNITE_MS 1100
#define SND_RETRACT_MS 1000
#define SND_BOOT_MS 1240
