#!/usr/bin/env python3
"""Install the real saber sounds on the SD-card image.

  python firmware/tools/get_saber_sounds.py

Downloads the ProffieOS default SD card (a ~200 MB zip, cached next to this script), takes the
"TeensySF" font from it and writes the blade sounds over the synthesized ones in
firmware/sd-card/MP3 and ADVERT: hum, ignite, retract, lockup, swings, clashes, blaster blocks.
Menu / UI / boot sounds stay as generated by make_sounds.py (run that one first).

It also writes firmware/lightsaber/sound_lengths.h (ignite/retract and per-track lengths).

TeensySF is by Fredrik Hubinette, CC BY-SA 4.0 (credit in firmware/sd-card/README.md).
"""
import io
import re
import urllib.request
import wave
import zipfile
from pathlib import Path

import numpy as np

HERE = Path(__file__).resolve().parent
FW = HERE.parent
SD = FW / "sd-card"
URL = "https://fredrik.hubbe.net/lightsaber/ProffieOS_SD_Card.zip"
CACHE = HERE / "out" / "ProffieOS_SD_Card.zip"
FONT = "ProffieOS_SD_Card/TeensySF/"

# our track -> source file in the font
MP3 = {2: "hum01", 3: "out02", 4: "in01", 5: "lock01"}
ADVERT = {
    1: "swng09", 2: "swng12", 3: "swng06", 4: "swng02",   # slow swings
    5: "swng01", 6: "swng08", 7: "swng16", 8: "swng03",   # fast swings
    9: "clsh03", 10: "clsh10", 11: "clsh01", 12: "clsh06",  # clashes
    13: "blst01", 14: "blst02", 15: "blst03", 16: "blst04",  # blaster blocks
}
TRIM = {"out02", "in01"} | set(ADVERT.values())  # a silent tail would delay the hum / the next effect


def load(z, name):
    w = wave.open(io.BytesIO(z.read(FONT + name + ".wav")))
    assert w.getnchannels() == 1 and w.getsampwidth() == 2 and w.getframerate() == 44100, name
    return np.frombuffer(w.readframes(w.getnframes()), dtype="<i2").astype(np.float64)


def trim(a, sr=44100):
    """Cut trailing silence (below 3 % of peak, 20 ms windows) and fade the last 40 ms."""
    win = sr // 50
    env = np.array([np.abs(a[i:i + win]).max() for i in range(0, len(a) - win, win)])
    last = max(i for i, e in enumerate(env) if e > env.max() * 0.03)
    a = a[:(last + 2) * win].copy()
    n = sr // 25
    a[-n:] *= np.linspace(1, 0, n)
    return a


def save(path, a):
    path.parent.mkdir(parents=True, exist_ok=True)
    with wave.open(str(path), "wb") as w:
        w.setnchannels(1)
        w.setsampwidth(2)
        w.setframerate(44100)
        w.writeframes(np.clip(a, -32768, 32767).astype("<i2").tobytes())


def main():
    if not CACHE.exists():
        CACHE.parent.mkdir(parents=True, exist_ok=True)
        print("downloading", URL)
        urllib.request.urlretrieve(URL, CACHE)
    z = zipfile.ZipFile(CACHE)
    lengths = {}
    for folder, table in (("MP3", MP3), ("ADVERT", ADVERT)):
        for track, src in table.items():
            a = load(z, src)
            if src in TRIM:
                a = trim(a)
            save(SD / folder / f"{track:04d}.wav", a)
            lengths[(folder, track)] = len(a) / 44100
            print(f"{folder}/{track:04d}.wav <- {src} ({len(a) / 44100:.2f}s)")

    # lengths of every main-channel track (ms), index = track number; the firmware stops one-shots
    # itself when they end, because the DFPlayer would otherwise restart or continue to the next file
    lens = [0]
    for t in range(1, 14):
        f = SD / "MP3" / f"{t:04d}.wav"
        with wave.open(str(f)) as w:
            lens.append(int(w.getnframes() * 1000 / w.getframerate()))
    ign, ret = lens[3] + 50, lens[4] + 50
    h = FW / "lightsaber" / "sound_lengths.h"
    h.write_text(f"""// Written by firmware/tools/get_saber_sounds.py - lengths (ms) of the main-channel tracks.
// If you swap the sound files, rerun the script (or edit these by hand).
#pragma once
#define SND_IGNITE_MS {ign}
#define SND_RETRACT_MS {ret}
#define SND_LENGTHS_MS {{{", ".join(map(str, lens))}}}  // index = track number
""")
    print(f"sound_lengths.h: ignite {ign} ms, retract {ret} ms, table {lens}")


if __name__ == "__main__":
    main()
